Implement calculator functionality.
laurandarius/CalculatorProject pull request #11
Opened 2019-04-23 12:21 UTC by laurandarius

Closes #5

2019-04-24 13:01 UTC, lgnstn requested changes

2019-04-24 13:01 UTC, lgnstn commented on src/components/Calculator.js
> +  const [result, setResult] = useState("0");
This should be a class not a function. The hooks are meant for exceptions. Also this one should be a container (I think you should have read about component and containers or smart components and dumb components).

2019-04-24 13:01 UTC, lgnstn commented on src/components/Calculator.js
> +      <Button
You can create a config array for the buttons with the props each needs and then iterate through it and render all of them at once.

2019-04-25 12:11 UTC, laurandarius commented
@lgnstn Please review this PR too :)

2019-05-07 07:32 UTC, lgnstn approved these changes

2019-05-07 07:32 UTC, merged