Create button component.
laurandarius/CalculatorProject pull request #9
Opened 2019-04-18 10:36 UTC by laurandarius

Closes #3

2019-04-19 09:54 UTC, laurandarius commented
@lgnstn PR is ready for review.

2019-04-23 12:59 UTC, lgnstn requested changes

2019-04-23 12:59 UTC, lgnstn commented on src/components/Display.js
> +const DisplayLayout = styled.div`
This component shouldn't be changed in this PR. Sorry for the misunderstanding :)

2019-04-23 12:59 UTC, lgnstn commented on src/components/Button.js
> +const Button = props => (
Add style for this component in this PR.

2019-04-23 16:13 UTC, laurandarius commented
@lgnstn Please review my PR.

2019-04-24 05:13 UTC, lgnstn requested changes

2019-04-24 05:13 UTC, lgnstn commented on src/components/Button.js
> +const Button = props => <ButtonLayout>{props.value}</ButtonLayout>;
Why did you remove the possibility to configure the size and the color?

2019-04-24 07:59 UTC, lgnstn approved these changes

2019-04-24 07:59 UTC, merged